fix issues on new hdp 2.2.4 version

diff --git a/guagua-client/src/main/bash/guagua-env b/guagua-client/src/main/bash/guagua-env
--- a/guagua-client/src/main/bash/guagua-env
+++ b/guagua-client/src/main/bash/guagua-env
@@ -63,11 +63,16 @@ if [ "${GUAGUA_CONF_DIR}" != "" -a -d "${GUAGUA_CONF_DIR}" ]; then
 fi
 # ---------------- HADOOP Environment Detection -------------------------------------#
 HADOOP_ROOT=""
-
+    
 # locate HADOOP_ROOT "which hadoop"
 HADOOP_CMD_PATH=`which hadoop 2>/dev/null`
+_status=`echo $?`
+if [ "${_status}" != "0" ]; then
+    echo "No hadoop command in PATH env, please configure, or you cannot run Shifu in your Hadoop cluster."
+    exit 1    
+fi
 # Check whether hadoop is installed under /usr/bin or not
-if [ "${HADOOP_CMD_PATH}" == "/usr/bin/hadoop" -a -d /usr/lib/hadoop ]; then
+if [ "${HADOOP_CMD_PATH}" == "/usr/bin/hadoop" -a -d /usr/lib/hadoop -a -d /usr/lib/hadoop/bin ]; then
     HADOOP_ROOT=/usr/lib/hadoop
 else
     # Check whether ${HADOOP_CMD_PATH}/../../lib exists or not
@@ -105,7 +110,7 @@ if [ "${HADOOP_ROOT}" != "" ]; then
         LD_LIBRARY_PATH="${HADOOP_ROOT}/lib/native":${LD_LIBRARY_PATH}  
     fi
 else
-    echo 'Hadoop is not configurated well, please check.'
+    echo 'Hadoop is not configured well, please check.'
     exit 1;
 fi
 
@@ -113,7 +118,11 @@ export LD_LIBRARY_PATH
 # ---------------- Detection End ---------------------------------------------------#
 
 # ---------------- Check Hadoop version  -------------------------------------------#
-VERSION=`${HADOOP_ROOT}/bin/hadoop version | head -n 1 | awk '{ print $2 }'`
+if [ "${HADOOP_ROOT}" != "" ]; then
+    VERSION=`${HADOOP_ROOT}/bin/hadoop version | head -n 1 | awk '{ print $2 }'`
+else
+    VERSION=`hadoop version | head -n 1 | awk '{ print $2 }'`
+fi
 VERSION_23=${VERSION:0:4}
 VERSION_2=${VERSION:0:1}
 
